### PR TITLE
Ignore tokens in shortcodes with comment syntax

### PR DESCRIPTION
**Pull request by jdbaldry**
I believe it would be a useful addition to support ignoring tokens that represent commented out shortcode contents. 

The syntax added to the test file is how Grafana escapes shortcodes in documentation: https://grafana.com/docs/writers-toolkit/write/shortcodes/#escaping-hugo-shortcodes.

I've naively extended the regular expressions with optional sequences after each opening and before each closing shortcode delimiter.
I've not tested any edge cases or even deeply interrogated the existing regular expressions to understand them, instead I'm relying on the `test.md` Markdown file and related `cmdtest` script to ensure I haven't introduced any issues.

### CODE REVIEW

**Comment by jdbaldry** [comment]
I need to spend some time understanding the tests because I don't see my uncommitted changes to the `Hugo/.vale.ini` file reflected in the test output.

**Comment by jdbaldry** [comment]
I updated the `ct` file to explicitly set `--config .vale.ini` and now I can see my changes reflected in the test output.

**Comment by jdbaldry** [comment]
I'm going through old PRs and cleaning things up.

I'll leave this open because I think it could be useful but do feel free to close if you don't have time justify the review of the even more complicated token regexp.

**Comment by jdkato** [comment]
Sorry for the delay -- the changes look good. I'll put out a new release soon.

**Comment by jdbaldry** [comment]
No worries at all, thanks for taking a look and for putting out the release!

**Pull request merged**
